# Generated by Django 5.1.4 on 2025-01-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationcode',
            name='used_by',
        ),
    ]
