# Generated by Django 5.1.4 on 2025-01-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('STU', 'Student'), ('ADM', 'Administration')], default='STU', max_length=100),
        ),
    ]
